# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
    
    - name: Build project
      run: npm run build
      
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        path: ./dist
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      pages: write
      id-token: write
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2.1.1
    
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.3
      with:
        # GitHub token
        token: ${{ secrets.GITHUB_TOKEN }}
        
